"""add more guards

Revision ID: b2b5bb6e8224
Revises: cb475b585876
Create Date: 2025-09-25 10:42:28.025746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b5bb6e8224'
down_revision = 'cb475b585876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('exit_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('check_out_time')

    # ### end Alembic commands ###
